import Navbar from "@/Components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/globals.css';
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
        {/* {children} */}
        <div style={{ paddingTop: '64px' }}> {/* Adjust '64px' based on the height of your navbar */}
          {children}
        </div>

        <Footer />
        </body>
      
    </html>
  );
}
